### ISSUE TITLE
add json methods that ignore non-json content

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#1]
This is particularly useful for `forEach`, but I could see it being used in `first` as well. The idea is that if it finds non-json, it will ignore that chunk instead of erroring.

Both `grandma` and my json toolkit (will) have this option to ignore content that they come across that cannot be parsed to json, meaning that I keep having to reimplement `forEach.json` myself to ignore errors instead of emitting the error on the stream.

Just a thought.

**Comment by stezu** [comment]
I like the idea, but I'm not sure what the API would look like. I guess I could provide an option to the methods to error/ignore non-json? I don't really like that idea. I could add a `foreach.maybeJson`.

**Comment by catdad** [comment]
`forEach.jsonOnly`?
`forEach.json.ignoreErrors`?

I ended up just adding a `through` transform, since I was already manipulating the stream anyway. It turns out that we have been using `through` all wrong... or at least not using the cool stuff.
