### ISSUE TITLE
implement #flatten

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#14]
This will specifically work with an object stream of arrays, and it will emit every element in those arrays as a separate element on the output stream. Basically, it will be used to reverse `batch` streams. See #7.

```javascript
input
  .pipe(ns.batch({ count: 5 })
  .pipe(doABatchThing)
  .pipe(ns.flatten())
  .pipe(output);
```

What happens when items being read are not arrays though? Do they just get re-emitted as is?

**Comment by stezu** [comment]
It looks like [Highland](http://highlandjs.org/#flatten) and [RxJS](http://stackoverflow.com/questions/37507101/in-rxjs-how-do-i-flatten-or-merge-a-stream-containing-both-normal-types-and-obs) both just re-emit non-arrays. I think the only options we have are to re-emit or error the stream.

I would accept an error if there was a chance we wanted to do something else in the future like flatten streams for example. Perhaps we can have a whitelist of types that re-emit and error for things like streams right now so it can be improved in the future?

**Comment by stezu** [comment]
Done #18
