### ISSUE TITLE
create a stream from an array

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#22]
So that I can take some dump input data and stream it.

Pseudo-code:

```javascript
ns.createStream.fromArray([1, 2, 3])
```

Or maybe go crazy:

```javascript
ns.createStream(randomObj, randomOtherValue, [1, 2, 3], someVar)
  .pipe(ns.flatten())
```

**Comment by stezu** [comment]
@catdad I added an implementation of `ns.fromArray`. It just takes the single argument, do you have any real interest in the multi-argument version?

**Comment by catdad** [comment]
I'm going to say no, for the purposed of this issue.
