### ISSUE TITLE
create stream from a callback function

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#24]
So that I can create streams from asynchronous things.

Pseudo-code:

```javascript
ns.createStream.fromCallback(fs.readdir, path.resolve('.'));
```

**Comment by stezu** [comment]
I think the pseudo-code above doesn't work for methods that use `this`. The RxJS observable method looks like this: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromnodecallback.md

That method also has a "selector" which is a function that allows you to select which callback params go into the stream, and that seems like it might be nice. I'm going to think about this one a bit and get back to it later.

**Comment by catdad** [comment]
If you pass in `fromCallback(function, function)`, what happens? Is that a selector or a context? I always hate seeing libs like this. I am guessing you don't feel too good about making people bind functions on their own?

**Comment by stezu** [comment]
I'm on the fence about binding the function. Because, if you're okay with binding, you don't need more than one parameter in `ns.fromCallback`:

```js
ns.fromCallback(fs.readdir.bind(this, path.resolve('.')))
```

**Comment by stezu** [comment]
For now I'm going to stick with the current implementation which only supports one argument. I can always add more arguments in the future if needed.
