### ISSUE TITLE
exposing flush method on collection methods

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#4]
How do you feel about exposing the flush on `filter`, `map`, and `reduce`?

I am doing a stupid thing -- I need to sort a stream, and was thinking about using a `reduce` to convert the stream to an array, and then sorting and serializing in the flush. Yeah, it's 4 lines of code, but I am wondering if that is common enough of a case to be relevant as an actual feature.

**Comment by stezu** [comment]
So, if I'm understanding you right, you're reducing to an array and then you want to sort/serialize the array before the next step in your stream. In that case, you could just use map for the sort/serialize step.

Like this:
```javascript
const nodeStream = require('node-stream');

fs.createReadStream('input.txt')
  .pipe(nodeStream.reduce((memo, item, next) => {
    next(null, [...memo, item]);
  }, []))
  .pipe(nodeStream.map((chunk, next) => {
    next(null, chunk.sort());
  }))
  .pipe(nodeStream.stringify());
```

**Comment by catdad** [comment]
Damn it, I always forget that you use object streams for everything. Yeah, that is a good point.

**Comment by stezu** [comment]
Well, mapping a bunch of strings would be annoying wouldn't it?

**Comment by catdad** [comment]
I don't know what you are talking about. Strings are great!
