### ISSUE TITLE
Consider sync variations on methods

### ISSUE THREAD

**Issue by stezu** [stezu/node-stream#5]
I find myself writing a lot of code like this:
```javascript
const nodeStream = require('node-stream');

fs.createReadStream('input.txt')
  .pipe(nodeStream.reduce((memo, item, next) => {
    next(null, [...memo, item]);
  }, []))
  .pipe(nodeStream.map((chunk, next) => {
    next(null, chunk.sort());
  }));
```

I think it would be nice if I could just return a value for simple modifications. Like this:
```javascript
const nodeStream = require('node-stream');

fs.createReadStream('input.txt')
  .pipe(nodeStream.reduce((memo, item) => {
    return [...memo, item];
  }, []))
  .pipe(nodeStream.map((chunk) => {
    return chunk.sort();
  }));
```

For people who like one liners, that could be simplified to:
```javascript
const nodeStream = require('node-stream');

fs.createReadStream('input.txt')
  .pipe(nodeStream.reduce((memo, item) => [...memo, item], []))
  .pipe(nodeStream.map(chunk => chunk.sort()));
```

I don't think I want to add more methods, I think I prefer auto-detection of sync vs non-sync. To do that, we can check the return value of the callback. If the value is undefined, we assume async, if the return value is anything else we assume sync and handle it appropriately.

If a value is returned, we will call the transform `next()` method asynchronously internally.

**Comment by stezu** [comment]
I've thought about it a bit more, and think a `function.length` approach might work better here since `nodeStream.map` (and others) can legitimately return `undefined` to remove items from the stream.

**Comment by catdad** [comment]
How do you feel about libs (and people) that do silly things like pars `arguments`? We've had problems with that with libs like Express.

```javascript
ns.map(function () {
  // I am evil
  var args = [].slice.call(arguments);
  var data = args.shift();
  var cb = args.pop();
  // is there stuff in the middle?... I don't care

  // do my thing
});
```

**Comment by stezu** [comment]
I was considering a `map.sync` but I think that would be kind of annoying to type out all the time. At this point, I prefer defaulting to the sync version and saying the async version will require the correct number of parameters.

It doesn't have the same issues that express has with the error handler so I'm overall okay with it. Since:
* any number of parameters lower than the async version uses the sync version, the stream always works.
* if you have the right number of parameters for the async version, you must use the last parameter for the stream to work.
* since you have to use the callback for the async path, obfuscation won't break the code.

The case you mention is the only one that isn't covered, and I don't think that is a valid use case.
